<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL($mot,$user)
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT v FROM ReclamationBundle:Reclamation v
                      WHERE v.etat =$mot AND v.user =$user");
        return $q->getResult();
    }
    public function findrec($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM ReclamationBundle:Reclamation e 
                WHERE e.description LIKE :str '
            )
            ->setParameter('str', $str.'%')
            ->getResult();
    }

}
